import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/components/common/theme-provider';

const iranYekanXFont = localFont({
  src: [
    { path: '../../public/fonts/IRANYekanXFaNum-Thin.woff', weight: '100' },
    {
      path: '../../public/fonts/IRANYekanXFaNum-UltraLight.woff',
      weight: '200',
    },
    { path: '../../public/fonts/IRANYekanXFaNum-Light.woff', weight: '300' },
    { path: '../../public/fonts/IRANYekanXFaNum-Regular.woff', weight: '400' },
    { path: '../../public/fonts/IRANYekanXFaNum-Medium.woff', weight: '500' },
    { path: '../../public/fonts/IRANYekanXFaNum-DemiBold.woff', weight: '600' },
    { path: '../../public/fonts/IRANYekanXFaNum-Bold.woff', weight: '700' },
    {
      path: '../../public/fonts/IRANYekanXFaNum-ExtraBold.woff',
      weight: '800',
    },
    { path: '../../public/fonts/IRANYekanXFaNum-Black.woff', weight: '900' },
    {
      path: '../../public/fonts/IRANYekanXFaNum-ExtraBlack.woff',
      weight: '950',
    },
    { path: '../../public/fonts/IRANYekanXFaNum-Heavy.woff', weight: '1000' },
  ],
  variable: '--font-iranYekanX',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${iranYekanXFont.variable} font-iranYekanX`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
