// mockBlogData.ts (or inline in BlogCarousel)
import { BlogItemProps } from '@/types/blog';

export const mockBlogData: BlogItemProps[] = [
  {
    id: 1,
    date: '2025-10-28T10:00:00',
    modified: '2025-10-28T12:30:00',
    slug: 'build-scalable-react-apps-2025',
    status: 'publish',
    link: 'https://example.com/blog/build-scalable-react-apps-2025',
    title: {
      rendered: 'How to Build Scalable React Applications in 2025',
    },
    content: {
      rendered:
        '<p>React has evolved significantly over the years...</p>'.repeat(50),
      markdown: '# Heading\nReact content in markdown...'.repeat(20),
      protected: false,
    },
    excerpt: {
      rendered:
        'Learn modern patterns and best practices to build performant and maintainable React applications at scale.',
      protected: false,
    },
    author: 1,
    featured_media: 101,
    comment_status: 'open',
    ping_status: 'open',
    sticky: false,
    template: '',
    format: 'standard',
    meta: {
      footnotes: '',
    },
    categories: [2, 5],
    tags: [10, 11, 12],
    tags_list: [
      {
        term_id: 10,
        name: 'react',
        slug: 'react',
        term_group: 0,
        term_taxonomy_id: 10,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 45,
        filter: 'raw',
      },
      {
        term_id: 11,
        name: 'typescript',
        slug: 'typescript',
        term_group: 0,
        term_taxonomy_id: 11,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 38,
        filter: 'raw',
      },
      {
        term_id: 12,
        name: 'performance',
        slug: 'performance',
        term_group: 0,
        term_taxonomy_id: 12,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 22,
        filter: 'raw',
      },
    ],
    amp_enabled: true,
    featured_image_url:
      'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&h=600&fit=crop',
    total_views_count: 12450,
  },
  {
    id: 2,
    date: '2025-10-25T14:30:00',
    modified: '2025-10-26T09:15:00',
    slug: 'nextjs-15-guide',
    status: 'publish',
    link: 'https://example.com/blog/nextjs-15-guide',
    title: {
      rendered: 'The Ultimate Guide to Next.js 15 Features',
    },
    content: {
      rendered:
        '<p>Next.js 15 introduces groundbreaking performance improvements...</p>'.repeat(
          40,
        ),
      markdown: '## Next.js 15\nPartial prerendering is here...'.repeat(15),
      protected: false,
    },
    excerpt: {
      rendered:
        'Explore the new features in Next.js 15 including partial prerendering, better caching, and AI-powered routing.',
      protected: false,
    },
    author: 1,
    featured_media: 102,
    comment_status: 'open',
    ping_status: 'open',
    sticky: true,
    template: '',
    format: 'standard',
    meta: {
      footnotes: '',
    },
    categories: [3],
    tags: [13, 14],
    tags_list: [
      {
        term_id: 13,
        name: 'nextjs',
        slug: 'nextjs',
        term_group: 0,
        term_taxonomy_id: 13,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 60,
        filter: 'raw',
      },
      {
        term_id: 14,
        name: 'ssr',
        slug: 'ssr',
        term_group: 0,
        term_taxonomy_id: 14,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 35,
        filter: 'raw',
      },
    ],
    amp_enabled: true,
    featured_image_url:
      'https://images.unsplash.com/photo-1627398242454-45c5a5c1a9b8?w=800&h=600&fit=crop',
    total_views_count: 18900,
  },
  {
    id: 3,
    date: '2025-10-20T09:15:00',
    modified: '2025-10-20T09:15:00',
    slug: 'tailwind-css-mastery',
    status: 'publish',
    link: 'https://example.com/blog/tailwind-css-mastery',
    title: {
      rendered: 'Mastering Tailwind CSS: From Zero to Hero',
    },
    content: {
      rendered: '<p>Tailwind CSS is a utility-first framework...</p>'.repeat(
        60,
      ),
      markdown: '```css\n@layer utilities { ... }\n```'.repeat(25),
      protected: false,
    },
    excerpt: {
      rendered:
        'A complete guide to mastering Tailwind CSS with advanced techniques, custom configs, and design systems.',
      protected: false,
    },
    author: 1,
    featured_media: 103,
    comment_status: 'open',
    ping_status: 'closed',
    sticky: false,
    template: '',
    format: 'standard',
    meta: {
      footnotes: '<sup>1</sup> Source: Tailwind Labs',
    },
    categories: [4, 6],
    tags: [15, 16, 17],
    tags_list: [
      {
        term_id: 15,
        name: 'tailwind',
        slug: 'tailwind',
        term_group: 0,
        term_taxonomy_id: 15,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 72,
        filter: 'raw',
      },
      {
        term_id: 16,
        name: 'css',
        slug: 'css',
        term_group: 0,
        term_taxonomy_id: 16,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 88,
        filter: 'raw',
      },
      {
        term_id: 17,
        name: 'design',
        slug: 'design',
        term_group: 0,
        term_taxonomy_id: 17,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 51,
        filter: 'raw',
      },
    ],
    amp_enabled: false,
    featured_image_url:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    total_views_count: 21500,
  },
  {
    id: 4,
    date: '2025-10-18T11:45:00',
    modified: '2025-10-19T14:20:00',
    slug: 'why-typescript-2025',
    status: 'publish',
    link: 'https://example.com/blog/why-typescript-2025',
    title: {
      rendered: 'Why TypeScript is Essential in 2025',
    },
    content: {
      rendered: '<p>TypeScript adoption has skyrocketed...</p>'.repeat(45),
      markdown: '```ts\ntype User = { name: string }\n```'.repeat(18),
      protected: false,
    },
    excerpt: {
      rendered:
        'Discover why TypeScript remains the gold standard for type-safe JavaScript development in modern teams.',
      protected: false,
    },
    author: 1,
    featured_media: 104,
    comment_status: 'open',
    ping_status: 'open',
    sticky: false,
    template: '',
    format: 'standard',
    meta: {
      footnotes: '',
    },
    categories: [5],
    tags: [11, 18],
    tags_list: [
      {
        term_id: 11,
        name: 'typescript',
        slug: 'typescript',
        term_group: 0,
        term_taxonomy_id: 11,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 38,
        filter: 'raw',
      },
      {
        term_id: 18,
        name: 'javascript',
        slug: 'javascript',
        term_group: 0,
        term_taxonomy_id: 18,
        taxonomy: 'post_tag',
        description: '',
        parent: 0,
        count: 95,
        filter: 'raw',
      },
    ],
    amp_enabled: true,
    featured_image_url:
      'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&h=600&fit=crop',
    total_views_count: 16700,
  },
];
